blueprints/open/__init__.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_user

from models import User
from passlib.hash import argon2

bp_open = Blueprint('bp_open', __name__)


@bp_open.get('/')
def index():
    return render_template("index.html")


@bp_open.get('/login')
def login_get():
    return render_template('login.html')


@bp_open.post('/login')
def login_post():
    email = request.form['email']
    password = request.form['password']
    user = User.query.filter_by(email=email).first()
    if user is None:
        flash('Wrong email or password')
        return redirect(url_for('bp_open.index'))

    if not argon2.verify(password, user.password):
        flash('Wrong email or password')
        return redirect(url_for('bp_open.login_get'))

    login_user(user)
    user.online = True

    from app import db
    db.session.commit()
    return redirect(url_for('bp_user.user_get'))


@bp_open.get('/signup')
def signup_get():
    return render_template('signup.html')


@bp_open.post('/signup')
def signup_post():
    name = request.form['name']
    email = request.form.get('email')
    password = request.form['password']
    hashed_password = argon2.using(rounds=10).hash(password)
    from controllers.user_controller import generate_rsa_keys
    public_key = generate_rsa_keys(name)
    user = User.query.filter_by(email=email).first()

    if user:
        flash("Email address is already in use")
        return redirect(url_for('bp_open.signup_get'))

    new_user = User(name=name, email=email, password=hashed_password, public_key=public_key)

    from app import db
    db.session.add(new_user)
    db.session.commit()

    return redirect(url_for('bp_open.login_get'))

blueprints/user/__init__.py
from flask import Blueprint, render_template, redirect, url_for, request
from flask_login import logout_user, login_required, current_user

from controllers.message_controller import create_message, get_user_messages, get_aes_message
from controllers.user_controller import get_all_but_current_user, get_user_by_id, get_public_key_by_id
import json


bp_user = Blueprint('bp_user', __name__)


@bp_user.get('/profile')
@login_required
def user_get():
    users = get_all_but_current_user()
    return render_template("user.html", users=users)


@bp_user.get('/logout')
def logout_get():
    user = current_user
    user.online = False

    from app import db
    db.session.commit()
    logout_user()
    return redirect(url_for('bp_open.index'))


@bp_user.get('/message/<user_id>')
def message_get(user_id):
    user_id = int(user_id)
    receiver = get_user_by_id(user_id)
    receiver_publickey = get_public_key_by_id(receiver.id)
    return render_template('message.html', receiver=receiver, receiver_publickey=receiver_publickey)


@bp_user.post('/message')
def message_post():
    title = request.form['cipher_title']
    body = request.form['cipher_body']
    aes_rsa = request.form['encrypted_aes']
    receiver_id = request.form['user_id']
    create_message(title, body, receiver_id, aes_rsa)
    return redirect(url_for('bp_user.user_get'))


@bp_user.get('/mailbox')
def mailbox_get():
    messages = get_user_messages()
    aes_rsa = get_aes_message()
    return render_template('mailbox.html', messages=messages, aes_rsa=aes_rsa)


@bp_user.get('/messages')
def get_messages():
    messages = get_user_messages()
    msg = messages[0]
    return render_template('Mailbox.html')

controllers/message_controller.py
from flask_login import current_user

from controllers.user_controller import get_user_by_id


def create_message(title, body, receiver_id, aes_rsa):
    from models import Message
    user = current_user
    message = Message(title=title, body=body, sender_id=user.id, aes_rsa=aes_rsa)
    receiver_id = int(receiver_id)
    receiver = get_user_by_id(receiver_id)

    message.receivers.append(receiver)
    from app import db
    db.session.add(message)
    db.session.commit()


def get_aes_message():
    from models import Message
    return Message.query.filter(Message.read == 0).filter(Message.aes_rsa).first()


def get_user_messages():
    return current_user.recv_messages


def get_unread_msg_count():
    user = current_user
    msg_count = 0

    for msg in user.recv_messages:
        if not msg.read:
            msg_count += 1

    return msg_count

controllers/user_controller.py
from Crypto.PublicKey import RSA
from flask_login import current_user


def get_all_but_current_user():
    from models import User
    user = current_user
    return User.query.filter(User.id != user.id).all()


def get_all_users():
    from models import User
    return User.query.all()


def get_public_key_by_id(user_id):
    from models import User
    return User.query.filter(User.id == user_id).filter(User.public_key).first()


def get_user_by_id(user_id):
    from models import User
    return User.query.filter(User.id == user_id).first()


def generate_rsa_keys(key_name, key_size=2048):
    key = RSA.generate(key_size)
    private_key = key.export_key()
    with open(f'./rsa_keys/{key_name}_private.pem', 'wb') as out_file:
        out_file.write(private_key)
    public_key = key.public_key().export_key()
    return public_key

templates/admin.html
{% extends "base-template.html" %}

{% block title %}
    Admin
{% endblock %}

{% block content %}
    <h1>This is the ADMIN page</h1>

{% endblock %}

templates/base-template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}" />


</head>
<body>

    {% if current_user.is_authenticated %}
        <a class="menu-item" href="{{ url_for('bp_user.user_get') }}">
        Home
    </a>
        <a class="menu-item" href="{{ url_for('bp_user.user_get') }}">
            Profile
        </a>

        <a class="menu-item" href="{{ url_for('bp_user.mailbox_get') }}">
            Mailbox
        </a>
        <a class="menu-item" href="{{ url_for('bp_user.logout_get') }}">
            Log Out
        </a>
        <a href="{{ url_for('bp_user.mailbox_get') }}">
            <i class="fa fa-fw fa-envelope-open" id="message-symbol"></i>
                <span class="sup" id="message-count"></span>
        </a>
    {% else %}
        <a class="menu-item" href="{{ url_for('bp_open.index') }}">
        Home
    </a>

     {% endif %}

    <hr />
    {% block content %}
    {% endblock %}

    <script>
        checkMessages();
        setInterval(checkMessages, 5000);

        function checkMessages() {
            fetch("http://127.0.0.1:5000/get_message_count")
                .then(response => response.json())
                .then(msgCount => {
                    let messageSymbol = document.getElementById("message-symbol");
                    let messageCount = document.getElementById("message-count");
                    if(msgCount.unreadMessageCount === 0) {
                        messageSymbol.classList.remove("fa-envelope");
                        messageSymbol.classList.add("fa-envelope-open");
                        messageCount.innerHTML = "";
                    }
                    else {
                        messageSymbol.classList.remove("fa-envelope-open");
                        messageSymbol.classList.add("fa-envelope");
                        messageCount.innerHTML = msgCount.unreadMessageCount;
                    }
                });
        }
    </script>

    {% block scripts %}
    {% endblock %}
</body>
</html>

templates/index.html
{% extends "base-template.html" %}

{% block content %}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification">
                {{ messages[0] }}.</a>
            </div>
        {% endif %}
    {% endwith %}

    <div class="index_main">
    <h1 class="index_h1">
        *ORN-Chat*
    </h1>

<div class="login_center">

    <form action="{{ url_for('bp_open.login_post') }}" method="POST">

    <div class="txt_field">
        <input type="email" name="email" placeholder="Your email address" /> <br />
        <input type="password" name="password" placeholder="Enter password" /> <br />
    </div>
    <input type="submit" value="Log In">
    <div class="pass">Forgot Password?</div>
    <div class="link_signup">
    <a href="{{ url_for('bp_open.signup_get') }}">Signup</a>
    </div>

    </form>
</div>
</div>
     <html lang="en">
    <head>
    <meta charset="UTF-8">
                 <meta name="viewport"
                       content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
                             <meta http-equiv="X-UA-Compatible" content="ie=edge">
                 <title>Document</title>
    </head>
    <body>
    
    </body>


    <video width="100" height="100" autoplay muted loop id="myVideo">
    <source src="{{ url_for('static', filename= 'earth.mp4') }}" >
    </video>
     </html>

{% endblock %}

templates/mailbox.html
{% extends "base-template.html" %}

{% block title %}
    Mailbox for {{ current_user.name }}
{% endblock %}

{% block content %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/4.0.0/crypto-js.min.js"></script>
    <script src="/static/js/rsa.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>


    <h1 id="main-heading">Mailbox</h1>

    <table>
        <tr>
            <th>Sender</th>
            <th>Sent</th>
            <th>Title</th>
            <th>Message Body</th>
        </tr>
        {% for message in messages %}
            <tr>
                <td>{{ message.sender.name }}</td>
                {% if message.sent_time is not none %}
                    <td>{{ message.sent_time.year }}-{{ message.sent_time.month }}-{{ message.sent_time.day }}</td>
                {% else %}
                    <td>-</td>
                {% endif %}
                <td id="encrypted">{{ "Title encrypted" }}</td>
                <td >{{ "Body encrypted" }}</td>
            </tr>
        {% endfor %}
    </table>


    <p>Upload private key</p>
    <input type="file" name="private_key" id="priv-file" enctype="multipart/form-data" />
    <button onclick="readPrivateKey()">Read Private Key</button><span id="priv-loaded"></span>
    <button onclick="rsaDecrypt()">Decrypt message</button>

    <br /> <br />
    <p id="decrypted_t"></p>
    <p id="decrypted_b"></p>

{% endblock %}
{% block scripts %}

    <script>
        let privateKey;

        function readPrivateKey() {
            let files = document.getElementById("priv-file").files;
            let file = files[0];
            let reader = new FileReader();

            reader.onloadend = function (event) {
                privateKey = event.target.result;
                privateKey = privateKey.replace(/(\r\n|\n|\r)/gm, "");

                document.getElementById("priv-loaded").innerHTML = "Private key loaded";
            };

            reader.readAsText(file);
        }

        function rsaDecrypt() {

            // Create a RSA object
            let rsaEncrypt = new JSEncrypt();
            // Set the private key we want to use for decryption
            rsaEncrypt.setPrivateKey(privateKey);
            // Decrypt the message
            let aes_decrypt = rsaEncrypt.decrypt({{ aes_rsa }});

            decrypt(aes_decrypt)


        }

        function decrypt(key) {
            let clearText_t = CryptoJS.AES.decrypt({{ messages.title }}, key);
            let clearText_b = CryptoJS.AES.decrypt({{ messages.body }}, key)
            document.getElementById("decrypted_t").innerHTML = clearText_t.toString();
            document.getElementById("decrypted_b").innerHTML = clearText_b.toString();

        }

    </script>
{% endblock %}

templates/message.html
{% extends "base-template.html" %}

{% block title %}
    Send a Message
{% endblock %}

{% block content %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/4.0.0/crypto-js.min.js"></script>
    <script src="/static/js/rsa.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <h1>Sending a message to {{ receiver.name }}</h1>

    <form action="{{ url_for('bp_user.message_post') }}" method="POST">
        <input class="message_title" id="title" type="text" placeholder="Message Title" /> <br />
        <input type="hidden" name="user_id" id="user_id" value="{{ receiver.id }}"/>
        <textarea id="body" placeholder="Message Body"></textarea> <br />
        <input type="hidden" name="cipher_title" id="cipher_title"/>
        <input type="hidden" name="cipher_body" id="cipher_body">
        <input type="hidden" name="encrypted_aes" id="encrypted_aes"/>
        <input onclick="rsaEncrypt()" class="send-button" type="submit" value="send" />
    </form>


{% endblock %}
{% block scripts %}
    <script>
        let encrypted_t;
        let encrypted_b
        let key;
        let public_key;

        function encrypt() {
            let message_title = document.getElementById("title").value;
            let message_body = document.getElementById("body").value;

            encrypted_t = CryptoJS.AES.encrypt(message_title, key);
            encrypted_b = CryptoJS.AES.encrypt(message_body, key);
            document.getElementById("cipher_title").innerHTML = encrypted_t;
            document.getElementById("cipher_body").innerHTML = encrypted_b;
        }

        function generateKey() {
            key = CryptoJS.lib.WordArray.random(16).toString();
            return key
        }

        function rsaEncrypt() {
            // Get the message to encrypt
            key = generateKey()

            encrypt()

            // Create a RSA object
            let rsaEncrypt = new JSEncrypt();
            public_key = {{ receiver_publickey }}
            // Set the public key we want to use for encryption
            rsaEncrypt.setPublicKey();
            // Encrypt the message
            let encrypted_aes = rsaEncrypt.encrypt(public_key);
            // Show the encrypted message on the page
            document.getElementById("encrypted_aes").innerHTML = encrypted_aes;



        }

    </script>
{% endblock %}

templates/signup.html
{% extends "base-template.html" %}

{% block content %}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification">
                {{ messages[0] }}. Go to <a href="{{ url_for('bp_open.login_get') }}">login page</a>
            </div>
        {% endif %}
    {% endwith %}

    <div class="signup_center">
    <h1>Signup</h1>

    <form action="{{ url_for('bp_open.signup_post') }}" method="POST">
        <div class="txt_field">
        <input type="text" name="name" placeholder="Enter your full name" /> <br />
        <input type="email" name="email" placeholder="Your email address" /> <br />
        <input type="password" name="password" placeholder="Enter password" /> <br />
        </div>

        <input type="submit" value="Sign Up">

    </form>
</div>
{% endblock %}

templates/user.html
{% extends "base-template.html" %}

{% block title %}
    User Page
{% endblock %}

{% block content %}
    <h1 id="main-heading">User Page</h1>
    <p>Hello {{ current_user.name }}</p>

    <table>
        <tr class="header_user">
            <th>User Name</th>
            <th>User Email</th>
            <th>Online</th>
        </tr>
        {% for user in users %}
            <tr>
                <td><a href="{{ url_for('bp_user.message_get', user_id=user.id) }}">{{ user.name }}</a></td>

                <td class="center-content">
                    {% if user.online %}
                        <div class="circle online"></div>
                    {% else %}
                        <div class="circle offline"></div>
                    {% endif %}
                </td>

            </tr>
        {% endfor %}
    <span>Press username to chat</span>
    </table>

{% endblock %}